# Generated by Django 2.2.17 on 2026-07-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GpcrStructureStatisticsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_entry_name', models.CharField(max_length=20)),
                ('uniprot_accession', models.CharField(max_length=20)),
                ('protein_name', models.CharField(max_length=100)),
                ('receptor_family', models.CharField(max_length=100, null=True)),
                ('receptor_class', models.CharField(max_length=100, null=True)),
                ('gene_name', models.CharField(max_length=100, null=True)),
                ('gene_entrez_id', models.CharField(max_length=100, null=True)),
                ('species_common_name', models.CharField(max_length=100, null=True)),
                ('st_inact_c', models.IntegerField()),
                ('st_interm_c', models.IntegerField()),
                ('st_act_c', models.IntegerField()),
                ('best_res_inact', models.FloatField(null=True)),
                ('best_res_interm', models.FloatField(null=True)),
                ('best_res_act', models.FloatField(null=True)),
                ('transd_gio_c', models.IntegerField()),
                ('transd_gq11_c', models.IntegerField()),
                ('transd_g1213_c', models.IntegerField()),
                ('transd_arrest_c', models.IntegerField()),
                ('transd_grks_c', models.IntegerField()),
                ('ligand_types_smmol_c', models.IntegerField()),
                ('ligand_types_pep_c', models.IntegerField()),
                ('limodgrp_stim_c', models.IntegerField()),
                ('limodgrp_inhib_c', models.IntegerField()),
                ('limodgrp_unk_c', models.IntegerField()),
                ('limod_apo_c', models.IntegerField()),
                ('limod_ag_c', models.IntegerField()),
                ('limod_ag_partial_c', models.IntegerField()),
                ('limod_allo_antag_c', models.IntegerField()),
                ('limod_antag_c', models.IntegerField()),
                ('limod_inv_ag_c', models.IntegerField()),
                ('limod_nam_c', models.IntegerField()),
                ('limod_pam_c', models.IntegerField()),
                ('limod_unk_c', models.IntegerField()),
            ],
            options={
                'db_table': 'table_gpcr_structure_statistics',
            },
        ),
        migrations.CreateModel(
            name='PdbTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_entry_name', models.CharField(max_length=20)),
                ('uniprot_accession', models.CharField(max_length=20)),
                ('gene_name', models.CharField(max_length=100, null=True)),
                ('gene_entrez_id', models.CharField(max_length=100, null=True)),
                ('protein_name', models.CharField(max_length=100)),
                ('receptor_family', models.CharField(max_length=100, null=True)),
                ('receptor_class', models.CharField(max_length=100, null=True)),
                ('fraction_of_wt_seq', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('species_common_name', models.CharField(max_length=100, null=True)),
                ('species_best', models.BooleanField(default=False)),
                ('identity_to_human', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('structure_type', models.CharField(max_length=100, null=True)),
                ('pdb_id', models.CharField(max_length=10)),
                ('resolution', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('resolution_best', models.BooleanField(default=False)),
                ('state', models.CharField(max_length=100, null=True)),
                ('gprot_bound_likeness', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('tm6_angle', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('signal_protein', models.CharField(max_length=100, null=True)),
                ('signal_protein_subtype', models.CharField(max_length=100, null=True)),
                ('signal_protein_note', models.CharField(max_length=100, null=True)),
                ('signal_protein_seq_cons', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('fusion', models.CharField(max_length=100, null=True)),
                ('antibody', models.CharField(max_length=100, null=True)),
                ('ligand', models.CharField(max_length=100, null=True)),
                ('ligand_function', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'table_pdb_data',
            },
        ),
        migrations.AddIndex(
            model_name='pdbtable',
            index=models.Index(fields=['uniprot_entry_name'], name='pdb_uniprot_entry_name_idx'),
        ),
        migrations.AddIndex(
            model_name='pdbtable',
            index=models.Index(fields=['gene_name'], name='pdb_gene_idx'),
        ),
        migrations.AddIndex(
            model_name='pdbtable',
            index=models.Index(fields=['protein_name'], name='pdb_protein_name_idx'),
        ),
        migrations.AddIndex(
            model_name='pdbtable',
            index=models.Index(fields=['receptor_family'], name='pdb_receptor_family_idx'),
        ),
        migrations.AddIndex(
            model_name='pdbtable',
            index=models.Index(fields=['receptor_class'], name='pdb_receptor_class_idx'),
        ),
        migrations.AddIndex(
            model_name='pdbtable',
            index=models.Index(fields=['fraction_of_wt_seq'], name='pdb_fraction_of_wt_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='pdbtable',
            index=models.Index(fields=['species_common_name'], name='pdb_species_name_idx'),
        ),
        migrations.AddIndex(
            model_name='pdbtable',
            index=models.Index(fields=['species_best'], name='pdb_species_best_idx'),
        ),
        migrations.AddIndex(
            model_name='pdbtable',
            index=models.Index(fields=['identity_to_human'], name='pdb_identity_to_human_idx'),
        ),
        migrations.AddIndex(
            model_name='pdbtable',
            index=models.Index(fields=['structure_type'], name='pdb_structure_type_idx'),
        ),
        migrations.AddIndex(
            model_name='pdbtable',
            index=models.Index(fields=['pdb_id'], name='pdb_id_idx'),
        ),
        migrations.AddIndex(
            model_name='pdbtable',
            index=models.Index(fields=['resolution'], name='pdb_resolution_idx'),
        ),
        migrations.AddIndex(
            model_name='pdbtable',
            index=models.Index(fields=['resolution_best'], name='pdb_resolution_best_idx'),
        ),
        migrations.AddIndex(
            model_name='pdbtable',
            index=models.Index(fields=['state'], name='pdb_state_idx'),
        ),
        migrations.AddIndex(
            model_name='pdbtable',
            index=models.Index(fields=['gprot_bound_likeness'], name='pdb_gprot_bound_likeness_idx'),
        ),
        migrations.AddIndex(
            model_name='pdbtable',
            index=models.Index(fields=['tm6_angle'], name='pdb_tm6_angle_idx'),
        ),
        migrations.AddIndex(
            model_name='pdbtable',
            index=models.Index(fields=['signal_protein'], name='pdb_signal_protein_idx'),
        ),
        migrations.AddIndex(
            model_name='pdbtable',
            index=models.Index(fields=['signal_protein_subtype'], name='pdb_sig_prot_subtype_idx'),
        ),
        migrations.AddIndex(
            model_name='pdbtable',
            index=models.Index(fields=['signal_protein_note'], name='pdb_sig_prot_note_idx'),
        ),
        migrations.AddIndex(
            model_name='pdbtable',
            index=models.Index(fields=['signal_protein_seq_cons'], name='pdb_sig_prot_seq_cons_idx'),
        ),
        migrations.AddIndex(
            model_name='pdbtable',
            index=models.Index(fields=['fusion'], name='pdb_fusion_idx'),
        ),
        migrations.AddIndex(
            model_name='pdbtable',
            index=models.Index(fields=['antibody'], name='pdb_antibody_idx'),
        ),
        migrations.AddIndex(
            model_name='pdbtable',
            index=models.Index(fields=['ligand'], name='pdb_ligand_idx'),
        ),
        migrations.AddIndex(
            model_name='pdbtable',
            index=models.Index(fields=['ligand_function'], name='pdb_ligand_function_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['uniprot_entry_name'], name='gsst_uniprot_entry_name_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['protein_name'], name='gsst_protein_name_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['receptor_family'], name='gsst_receptor_family_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['receptor_class'], name='gsst_receptor_class_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['gene_name'], name='gsst_gene_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['species_common_name'], name='gsst_species_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['st_inact_c'], name='gsst_st_inact_c_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['st_interm_c'], name='gsst_st_interm_c_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['st_act_c'], name='gsst_st_act_c_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['best_res_inact'], name='gsst_best_res_inact_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['best_res_interm'], name='gsst_best_res_interm_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['best_res_act'], name='gsst_best_res_act_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['transd_gio_c'], name='gsst_transd_gio_c_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['transd_gq11_c'], name='gsst_transd_gq11_c_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['transd_g1213_c'], name='gsst_transd_g1213_c_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['transd_arrest_c'], name='gsst_transd_arrest_c_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['transd_grks_c'], name='gsst_transd_grks_c_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['ligand_types_smmol_c'], name='gsst_ligand_types_smmol_c_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['ligand_types_pep_c'], name='gsst_ligand_types_pep_c_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['limodgrp_stim_c'], name='gsst_limodgrp_stim_c_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['limodgrp_inhib_c'], name='gsst_limodgrp_inhib_c_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['limodgrp_unk_c'], name='gsst_limodgrp_unk_c_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['limod_apo_c'], name='gsst_limod_apo_c_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['limod_ag_c'], name='gsst_limod_ag_c_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['limod_ag_partial_c'], name='gsst_limod_ag_partial_c_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['limod_allo_antag_c'], name='gsst_limod_allo_antag_c_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['limod_antag_c'], name='gsst_limod_antag_c_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['limod_inv_ag_c'], name='gsst_limod_inv_ag_c_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['limod_nam_c'], name='gsst_limod_nam_c_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['limod_pam_c'], name='gsst_limod_pam_c_idx'),
        ),
        migrations.AddIndex(
            model_name='gpcrstructurestatisticstable',
            index=models.Index(fields=['limod_unk_c'], name='gsst_limod_unk_c_idx'),
        ),
    ]
